module.exports = [
    "Snails have a strong sense of smell and can detect food and mates from a distance.",
    "Some snails can hibernate for years if the conditions are not ideal.",
    "The world's largest land snail is the Giant African Land Snail, which can grow up to 12 inches.",
    "Snails have thousands of teeth, some species can have as many as 25,000 teeth.",
    "Snail slime contains anti-aging compounds like collagen and elastin.",
    "Some snails are hermaphrodites, meaning they have both male and female reproductive organs.",
    "The fastest snail can move at a speed of 0.03 miles per hour.",
    "Snails produce a mucus trail that helps them glide smoothly and prevents dehydration.",
    "Certain species of snails can regenerate lost body parts, such as eyes or tentacles.",
    "A snail can sleep for several years under the right conditions.",
    "Some marine snails have a shell so thick that they can survive extreme ocean pressure.",
    "A snail’s shell grows in an outward spiral, and the shape is determined by its genetic makeup.",
    "Snail slime is being studied for medical applications, including wound healing.",
    "Some species of snails are considered endangered due to habitat destruction and invasive species.",
    "Snails communicate using chemical signals called pheromones to find mates.",
    "A garden snail can travel up to 40 meters in one night under optimal conditions.",
    "Snails can live in both freshwater and saltwater environments.",
    "Some snails have a protective ‘trapdoor’ called an operculum that can close the opening of their shell.",
    "The smallest snail species in the world is about the size of a pinhead.",
    "Snails have unique eyes located on the tips of their tentacles.",
    "Some species of snails can live for up to 10 years.",
    "Marine snails often have brightly colored shells to help them blend in with their environment.",
    "The number of tentacles on a snail varies depending on the species, with most having two pairs.",
    "Snails are highly sensitive to temperature changes and need specific conditions to survive.",
    "Certain species of snails can secrete a substance that repels predators.",
    "A snail’s mucus trail is actually made of protein and water and helps it stick to surfaces.",
    "Some snails are equipped with shells that are pointed to reduce the risk of predators eating them.",
    "Snails can recognize their offspring from others due to their unique scent.",
    "Some species of snails engage in ‘love dart’ behavior, where they shoot a sharp, calcareous dart into their mate during reproduction.",
    "Snails can have up to 25,000 teeth located on a structure called a radula.",
    "The radula of a snail works like a rasp, helping the snail scrape food from surfaces.",
    "Some snails can climb vertical surfaces like walls or trees, using their mucus for traction.",
    "The shell of a snail is made from calcium carbonate, similar to the material in limestone.",
    "Snail eggs can hatch anywhere from 1 to 3 weeks after they are laid, depending on temperature and moisture.",
    "Snails are considered to be one of the oldest creatures on Earth, with fossil records dating back more than 500 million years.",
    "The largest species of sea snail, the Australian trumpet snail, can grow to over 2 feet in length.",
    "Some snails have shells that grow in perfect spirals, while others have more irregular shapes.",
    "Some species of snails are hermaphrodites, meaning they can reproduce alone by self-fertilization.",
    "The common garden snail (*Cornu aspersum*) can travel at a speed of about 0.013 meters per second.",
    "Snails can often be found in moist, cool environments like forests, gardens, and even caves.",
    "Certain snails are edible and are considered a delicacy in some cultures, such as escargot in France.",
    "Aquatic snails use gills to breathe underwater, while land snails use lungs to breathe air.",
    "The lifespan of a snail can vary greatly depending on the species, but many species live around 2 to 5 years.",
    "Snails can carry parasites, including the dangerous rat lungworm, which can affect humans.",
    "Snails have been used in traditional medicine for centuries, particularly in Asia and Europe.",
    "The mucus produced by some snails is used in skincare products because it contains hydrating and anti-inflammatory properties.",
    "Snails often carry parasites, such as flukes, which can affect birds, fish, and amphibians.",
    "Snail shells are used by many species of animals for shelter, including hermit crabs.",
    "Some species of snails have shells that change color based on their diet or environmental factors.",
    "Certain species of snails can go without food for months, entering a state of dormancy to conserve energy.",
    "In some cultures, snail shells are used in jewelry, art, and even as currency.",
    "Snail mucus is sometimes used as a natural remedy for soothing burns or skin irritation.",
    "The radula of a snail is covered in hundreds of tiny, backward-facing teeth, allowing them to scrape off plant material.",
    "Snails have a thick, protective outer layer on their shells that helps prevent dehydration in dry conditions.",
    "Some snails have evolved to live in extreme environments, such as hot springs or acidic waters.",
    "In ancient Rome, snails were used as a food source and were considered a luxury item.",
    "Invasive snail species can be a major pest in agriculture, feeding on crops and damaging plants.",
    "Snails play a crucial role in ecosystems by decomposing organic matter and recycling nutrients.",
    "Snails can detect light and dark, and some species can even sense UV light.",
    "The color of a snail’s shell can sometimes be affected by its environment, such as sunlight exposure.",
    "The shells of some snails are incredibly durable, while others are thin and fragile.",
    "Snails are typically herbivores, but some species are carnivorous and will feed on small insects and other animals.",
    "Some snails are capable of surviving harsh, dry conditions by sealing themselves in their shells until moisture returns.",
    "The slime produced by snails is used to protect their soft bodies from rough surfaces.",
    "Some snails can live in brackish water, which is a mix of saltwater and freshwater.",
    "Some species of snails can even climb vertical glass surfaces when kept in captivity.",
    "The common garden snail (*Cornu aspersum*) is one of the most widely recognized snail species.",
    "Some snails have evolved bright colors and markings to warn predators of their toxicity or bad taste.",
    "The shape and pattern of a snail’s shell can help protect it from predators by camouflaging it in its environment.",
    "Marine snails are essential to the marine food chain and serve as food for many fish and seabirds.",
    "Certain types of freshwater snails can host parasites that affect other species of aquatic animals.",
    "Snails are sometimes used in laboratories for research on locomotion, genetics, and neurobiology.",
    "Snails use their slime for more than just movement—it helps them adhere to surfaces and move through difficult terrain.",
    "Some snails are used as bioindicators to monitor the health of aquatic ecosystems, as they are sensitive to pollution.",
    "The spiral shape of many snail shells may have evolved to make them more resistant to predators and environmental stress.",
    "Some snails, like the *Pomacea canaliculata*, are considered a major agricultural pest in rice fields.",
    "In many cultures, snails are believed to have magical or medicinal properties, often related to their ability to heal or regenerate.",
    "Snails are known to have a highly developed sense of smell, which they use to navigate and find food.",
    "The number of shells a snail has is a result of its genetics, and the size of the shell increases as the snail grows.",
    "Some snails, like the *Achatina achatina*, are known to be able to live for several years without food or water.",
    "The ability of snails to regenerate lost body parts makes them a subject of interest for medical research into regeneration and healing.",
    "Some snails live in extreme environments, such as volcanoes or geothermal areas, and have adapted to survive high temperatures.",
    "Snails have been part of human diets for thousands of years, particularly in Mediterranean and Asian cuisines.",
    "Certain species of snails are important to ecosystems as pollinators for certain types of plants.",
    "Some snails, such as *Conus* species, are known for their venomous sting, which they use to catch prey.",
    "The shells of some snails are so strong that they can be used as tools or building materials in some cultures.",
    "Snail shells are sometimes used in ancient rituals and ceremonies, particularly in Native American and African cultures.",
    "Snails are among the oldest creatures on Earth, with fossils dating back more than 500 million years.",
    "Snails have been shown to have a highly sophisticated nervous system, and their reactions to stimuli can be studied to understand neurobiology.",
    "Some snails are known for their ability to produce an extremely sticky mucus, which helps them catch prey or escape from danger.",
    "The largest snail in the world, the *Achatina achatina*, can grow up to 30 cm long and weigh several pounds.",
    "Snails can use their slime to glide over rough or jagged surfaces without injuring their bodies.",
    "Some species of snails are capable of reproducing in unusual ways, including asexual reproduction through cloning.",
    "In some cultures, snails are believed to bring good luck or fortune, particularly in ancient traditions.",
    "Certain species of snails can produce defensive slime that can make them difficult for predators to eat.",
    "The fastest snail species can move at a maximum speed of around 0.03 miles per hour.",
    "Some snails live in caves, where they are adapted to low-light and high-humidity environments."
  ];
  